# Generated by Django 5.0.1 on 2024-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_profile_options_remove_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
