# Generated by Django 4.2.7 on 2023-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_catalog_description_catalog_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(default='C:\\Users\\Asus\\Desktop\\Python\\justcode_python\\django_project\\store\\store\\main\\media\\empty.jpg', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
