# Generated by Django 4.2.7 on 2023-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_catalog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(default='store\\main\templates\\empty.jpg', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
