# Generated by Django 3.1.7 on 2024-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231221_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='email клиента'),
        ),
    ]
